class Window:
    def draw(self, stdscr, y_start: int, height: int, width: int): ...

    def handle_input(self, key): ...


class ListWindow(Window): ...


class NoteWindow(Window): ...


class AddWindow(Window): ...
